version: 2

sphinx:
  configuration: docs/source/conf.py

python:
  version: 3.8
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: .

artifacts:
  - path: docs/build/html
    destination: html

build:
  image: latest
  use-virtualenv: true

