# .github/workflows/draft-pdf.yml

permissions:
  contents: write   # needed to create/upload a Release

on:
  push:
    tags:
      - 'v*'        # run when you push v1.2.3 style tags

jobs:
  paper-draft:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # ... your existing steps that call openjournals/openjournals-draft-action
      # and produce paper/paper.pdf ...

      - name: Upload artifact (paper.pdf)
        uses: actions/upload-artifact@v4
        with:
          name: paper
          path: paper/paper.pdf

      # ⬇️ Replace EndBug/add-and-commit with these two steps ⬇️
      - name: Create release (if not exists)
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload paper.pdf to the release
        uses: softprops/action-gh-release@v2
        with:
          files: paper/paper.pdf
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
