name: Lint with flake8 and black

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    name: Code Linting and Autoformat
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install flake8 and black
        run: |
          python -m pip install --upgrade pip
          pip install flake8 black

      - name: Run flake8
        id: flake8
        continue-on-error: true
        run: |
          echo "🔍 Running flake8..."
          flake8 ManipulaPy tests --max-line-length=88

      - name: Check code style with black
        id: black_check
        continue-on-error: true
        run: |
          echo "🧹 Checking black formatting..."
          black --check ManipulaPy tests

      - name: Autoformat and push fixes if needed
        if: steps.flake8.outcome == 'failure' || steps.black_check.outcome == 'failure'
        run: |
          echo "🔧 Autoformatting with black due to lint failure..."
          black ManipulaPy tests

          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add ManipulaPy tests
          git commit -m "style: autoformat with black 🧹" || echo "Nothing to commit"
          git push || echo "Nothing to push"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

