name: Lint with flake8 and black

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    name: Code Linting
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: true  # required for committing

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install flake8 and black
        run: |
          pip install --upgrade pip
          pip install flake8 black

      - name: Run flake8
        run: |
          flake8 ManipulaPy tests --max-line-length=88

      - name: Check code style with black
        run: |
          black --check ManipulaPy tests

  autofix:
    name: Auto-format with Black and Push
    runs-on: ubuntu-latest
    needs: lint
    if: always()  # Run regardless, but check for actual changes
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: true  # required to push

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install black
        run: pip install black

      - name: Run Black Auto-format
        run: black ManipulaPy tests

      - name: Commit and Push if changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          if [[ `git status --porcelain` ]]; then
            git add ManipulaPy tests
            git commit -m "🔧 Auto-format code with Black"
            git push
          else
            echo "✅ No formatting changes to commit."
          fi
